# Generated by Django 5.2.7 on 2025-10-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMGs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='imagen',
        ),
        migrations.AddField(
            model_name='img',
            name='ruta',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
