# Generated by Django 4.2.20 on 2025-10-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource_chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('performance_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='performance_chart.performancechart')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_chart.resourcechart')),
            ],
        ),
    ]
