# Generated by Django 4.2.20 on 2025-10-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_chart', '0001_initial'),
        ('performance_chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancechart',
            name='cantidad',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancechart',
            name='recurso',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='resource_chart.resourcechart'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PerformanceResource',
        ),
    ]
