# Generated by Django 4.2.20 on 2025-10-27 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDFs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf')),
            ],
        ),
    ]
