# Generated by Django 5.2.7 on 2026-03-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDFs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('reglamento', 'Reglamento'), ('estatuto', 'Estatuto'), ('ley', 'Ley'), ('decreto', 'Decreto'), ('resolucion', 'Resolución'), ('documentacion junta', 'Documentación Junta'), ('documentacion directorio', 'Documentación Directorio'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('archivado', 'Archivado')], default='borrador', max_length=16)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf')),
            ],
        ),
    ]
