# Generated by Django 5.2.7 on 2025-10-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='archivo',
        ),
        migrations.AddField(
            model_name='pdf',
            name='ruta',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
