# Generated by Django 5.2.7 on 2026-03-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=32)),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuantifiedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=255)),
                ('performance_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_table.performancetable')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_table.resourcechart')),
            ],
            options={
                'unique_together': {('performance_table', 'recurso')},
            },
        ),
        migrations.AddField(
            model_name='performancetable',
            name='recursos',
            field=models.ManyToManyField(related_name='performance_tables', through='performance_table.QuantifiedResource', to='performance_table.resourcechart'),
        ),
    ]
