# Generated by Django 5.2.7 on 2026-03-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechart',
            name='categoria',
            field=models.CharField(choices=[('Materiales', 'Materiales'), ('Mano de Obra', 'Mano de Obra'), ('Herramientas y Equipo', 'Herramientas y Equipo')], default='Materiales', max_length=50),
        ),
    ]
