# Generated by Django 5.2.7 on 2026-03-28 01:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDFs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('salario', models.CharField(blank=True, max_length=86, null=True)),
                ('tipo_contrato', models.CharField(max_length=86)),
                ('requisitos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('responsabilidades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=16)),
                ('descripcion', models.TextField()),
                ('sobre_empresa', models.TextField(blank=True, null=True)),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PDFs.pdf')),
            ],
        ),
    ]
