# Generated by Django 5.2.7 on 2025-11-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFs', '0002_remove_pdf_archivo_pdf_ruta'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf'),
        ),
    ]
