# Generated by Django 5.2.7 on 2025-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='nombre_empresa',
            field=models.CharField(default='smth', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requisitos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsabilidades',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salario',
            field=models.CharField(default='50$', max_length=86),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='ubicacion',
            field=models.CharField(default='smth', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
