# Generated by Django 5.2.7 on 2026-04-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDFs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('anio', models.CharField(max_length=4)),
                ('categoria', models.CharField(choices=[('Ingeniería Estructural', 'Ingeniería Estructural'), ('Ingeniería Hidráulica', 'Ingeniería Hidráulica'), ('Ingeniería Sanitaria', 'Ingeniería Sanitaria'), ('Vias y Transporte', 'Vias y Transporte'), ('Ingeniería Geotécnica', 'Ingeniería Geotécnica'), ('Gerencias de la Construcción', 'Gerencias de la Construcción'), ('otros', 'Otros')], max_length=50)),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('borrador', 'Borrador'), ('archivado', 'Archivado')], max_length=20)),
                ('autor', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf')),
            ],
        ),
    ]
