# Generated by Django 4.2.20 on 2025-10-27 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDFs', '0001_initial'),
        ('IMGs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMGs.img')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf')),
            ],
        ),
    ]
