# Generated by Django 5.2.7 on 2025-11-03 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMGs', '0002_remove_img_imagen_img_ruta'),
        ('PDFs', '0002_remove_pdf_archivo_pdf_ruta'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IMGs.img'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PDFs.pdf'),
        ),
        migrations.AlterField(
            model_name='news',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
