# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_categoria_news_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='resumen',
            field=models.TextField(default='smth'),
            preserve_default=False,
        ),
    ]
