# Generated by Django 5.2.7 on 2025-11-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=16),
        ),
    ]
