# Generated by Django 4.2.20 on 2025-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=128)),
                ('RNI', models.CharField(max_length=50)),
                ('RNIC', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateField()),
                ('departamento', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos_users/')),
            ],
        ),
    ]
