# Generated by Django 5.2.7 on 2026-03-28 01:22

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IMGs', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(choices=[('admin_ciudad', 'Admin Ciudad'), ('admin_general', 'Admin General')], default='admin_ciudad', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarioadmin_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarioadmin_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rnic', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('rni', models.CharField(error_messages={'unique': 'Este RNI ya esta registrado.'}, max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('registro_empleado', models.CharField(choices=[('empleado', 'Empleado'), ('desempleado', 'Desempleado')], default='desempleado', max_length=16)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=16)),
                ('certificaciones', models.JSONField(default=list)),
                ('mail', models.CharField(blank=True, max_length=32)),
                ('rol', models.CharField(default='Usuario', editable=False, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuariocomun_groups', to='auth.group')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IMGs.img')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuariocomun_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
