# Generated by Django 5.2.7 on 2026-03-28 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocomun',
            name='rnic',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
