# Generated by Django 5.2.7 on 2025-10-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='ruta_foto',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
