# Generated by Django 5.2.7 on 2025-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_foto_user_ruta_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registro_empleado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
