# Generated by Django 5.2.7 on 2026-03-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField()),
                ('employed_users', models.IntegerField()),
                ('employment_rate', models.FloatField()),
                ('specialties_breakdown', models.JSONField(default=list)),
                ('state_breakdown', models.JSONField(default=list)),
                ('total_users_growth', models.FloatField(default=0.0)),
                ('employment_rate_growth', models.FloatField(default=0.0)),
                ('state_growth_breakdown', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
